### ISSUE TITLE
if my planning horizon is 8 years, the bar diagram shows the 9th year too

### ISSUE THREAD

**Issue by benktesh** [benktesh/biofuelSouth#1]

**Comment by benktesh** [comment]
I can see label for 9th year, but no bar graph for that. If I remove the label, then the line on the right edge will be gone.
![image](https://cloud.githubusercontent.com/assets/1903380/5890387/a440038e-a41d-11e4-92da-3e5cf7c4c843.png)

The potential alternate could be this:
![image](https://cloud.githubusercontent.com/assets/1903380/5890390/d1efc65c-a41d-11e4-9559-075640e7beac.png)

Let me know which one you think we should put.

**Comment by NeelamPoudyal** [comment]
I think I had meant to say the label for year 9 appears, where the planning period is 8 years only. If we can somehow stop the labeling at 8 years, its all good.

**Comment by benktesh** [comment]
so second image in that issue tracker? ----------------------------------------------
Benktesh D. Sharma
7549 Carrington Drive Apt H
Madison, WI 53719

Tel: +1 510 316 4927
E-mail: benktesh@yahoo.com

**Comment by benktesh** [comment]
----------------------------------------------
Benktesh D. Sharma
7549 Carrington Drive Apt H
Madison, WI 53719

Tel: +1 510 316 4927
E-mail: benktesh@yahoo.com

**Comment by NeelamPoudyal** [comment]
Yes.
Sorry, I did not see the images in last email. Messages were partially downloaded in my part.

**Comment by benktesh** [comment]
ok. no problem. Why are you still awake? ----------------------------------------------
Benktesh D. Sharma
7549 Carrington Drive Apt H
Madison, WI 53719

Tel: +1 510 316 4927
E-mail: benktesh@yahoo.com

**Comment by benktesh** [comment]
Resolved. Please verify. 
Once verified, you can hit the 'Close and Comment' button. Then we will know that this bug was done for good. We an also reopen the ticket in future, should we see that the issue re-emerged.

**Comment by NeelamPoudyal** [comment]
Yes, sir. Awake and alive.:)

**Comment by benktesh** [comment]
Sir my question was not 'are you'. It was 'why are you'. I needed to because I work for your mostly during weekends :) so I have to be awake. ----------------------------------------------
Benktesh D. Sharma
7549 Carrington Drive Apt H
Madison, WI 53719

Tel: +1 510 316 4927
E-mail: benktesh@yahoo.com

**Comment by NeelamPoudyal** [comment]
Haha, did not even read the whole question.  Short answer, too much work these days. Long one, I am trying get some field sampling plan finalized for visitor estimation in TVA controlled lands this summer season, and that has kept me working nights and weekends.

**Comment by NeelamPoudyal** [comment]
Its been interesting that every time I bookmark our webpage, some link about 401k benefit is bookmarked. I don’t know what the heck is up with my MacBook Air.

**Comment by benktesh** [comment]
I believe this issue is closed.

**Comment by NeelamPoudyal** [comment]
Saw that but missed to close in gitmo.:-)

Sent from my iPhone

On Jan 31, 2015, at 10:15 AM, "Benktesh Sharma" <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe this issue is closed.
