### ISSUE TITLE
Display alert message when woody crop is selected in DSS input steps

### ISSUE THREAD

**Issue by benktesh** [benktesh/biofuelSouth#61]
Display an alert message indicating that the production and cost data are based on regional/national average for woody crops when Pine is selected. Likewise the message should be altered to indicate that production data alone is based on regional average for poplar and willow.

**Comment by benktesh** [comment]
Please review.

**Comment by NeelamPoudyal** [comment]
Looks great. We should add in the same msg box a tab to allow "proceed anyway" or "go back"?

**Comment by benktesh** [comment]
No we cannot add proceed in that box. That msg is displayed immediately after making selection of a woody crop.

**Comment by NeelamPoudyal** [comment]
ok

**Comment by NeelamPoudyal** [comment]
Btw, lets talk whenever you are ready. I will be in front f computer for the next 60 minutes.

**Comment by benktesh** [comment]
Yes. On another call. Will be with you after this call.

**Comment by NeelamPoudyal** [comment]
ok
