### ISSUE TITLE
bale picture in About page

### ISSUE THREAD

**Issue by NeelamPoudyal** [benktesh/biofuelSouth#8]
Bale picture is too big, can be made similar to IBSS logo and both pictures in right hand side of the About Page, (texts on BDSS and IBSS on left hand side)

**Comment by benktesh** [comment]
Done. I tried to make the image to left. Please let me know if the image should appear to the right.

**Comment by NeelamPoudyal** [comment]
let the bale picture be in the right side, just like the IBSS logo.

**Comment by benktesh** [comment]
Changed as ordered. Please verify. Thanks.
