### ISSUE TITLE
Also, lets considering adding a map (focusing the county) in side of summary page.

### ISSUE THREAD

**Issue by benktesh** [benktesh/biofuelSouth#88]

**Comment by benktesh** [comment]
Done

**Comment by NeelamPoudyal** [comment]
Looks good. I did not see the county boundary drawn on map but it is centered that county. Should be fine. I would like to switch the location of comparison graph and the map box though. I think we can have map right under the crop picture. The comparison chart can be where map currently is  (under the “comparison with other crops” section)
