### ISSUE TITLE
Add values for “average cost per acre” and “average production per acre” in result's assumption tab

### ISSUE THREAD

**Issue by benktesh** [benktesh/biofuelSouth#90]
The input data and assumption page currently does not show value for “average cost per acre” and “average production per acre”

**Comment by NeelamPoudyal** [comment]
I think the Atlas below also has county level  yield data for sorghum and woody crop (I will found our out which woody crop/s they use for this layer), to expand our crop selection menu.

http://biomassatlas.org/biowebgis/

**Comment by benktesh** [comment]
I have moved the 'http://biomassatlas.org/biowebgis/' review task to [https://github.com/benktesh/biofuelSouth/issues/95].

The assumption page is currently showing the values for average cost and production.
